name: Continous integration

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
        section:
          - formatting
          - typing
          - coverage
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Test code sanity using tox -e ${{ matrix.section }}
        run: tox -e ${{ matrix.section }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    needs: sanity
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e py3
